from turtle import *
s=Screen()
t=Turtle()
s.bgcolor("light blue")
t.turtlesize(1)
t.speed("fastest")
#Sole
t.color("yellow")
t.penup()
t.goto(580,180)
t.pendown()
extent1=3.14*80**2
t.circle(radius=80,extent=extent1,steps=20)

#girandola aperta colorata
t.penup()
t.goto(-400,250)
t.pendown()
angle=t.heading()
print("angle1=",angle)
t.right(206)
angle2=t.heading()
print("angle2=",angle2)
t.right(90)
a=12
b=30
y=(a**2+b**2)**(1/2)
t.left(45)
for i in range(0,1):
    t.begin_fill()
    t.color("red")
    t.forward(y)
    t.right(90)
    t.forward(y)
    t.right(135)
    t.forward(2 * b)
    t.right(45)
    t.end_fill()
for i in range(1,2):
    t.begin_fill()
    t.color("green")
    t.forward(y)
    t.right(90)
    t.forward(y)
    t.right(135)
    t.forward(2 * b)
    t.right(45)
    t.end_fill()
for i in range(2,3):
    t.begin_fill()
    t.color("yellow")
    t.forward(y)
    t.right(90)
    t.forward(y)
    t.right(135)
    t.forward(2 * b)
    t.right(45)
    t.end_fill()
for i in range(4,5):
    t.begin_fill()
    t.color("blue")
    t.forward(y)
    t.right(90)
    t.forward(y)
    t.right(135)
    t.forward(2 * b)
    t.right(45)
    t.end_fill()
#girandola

    t.penup()
    t.goto(-310,210)
    t.pendown()
    angle3=t.heading()
    print("angle3=",angle3)
    t.right(45)

    b = 12
    altezza = b / 2
    k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
    t.begin_fill()
    t.color("red")
    for i in range(0,2):
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
    t.end_fill()

    #girandola
    t.penup()
    t.goto(-530,210)
    t.pendown()
    t.color("orange")
    t.begin_fill()
for i in range(0,2):
    t.left(45)
    t.forward(k)
    t.right(90)
    t.forward(k)
    t.right(135)
    t.forward(b)
    t.right(90)
    t.left(45)
    t.forward(k)
    t.right(90)
    t.forward(k)
    t.right(135)
    t.forward(b)
    t.right(90)
t.end_fill()

t.penup()
t.goto(0,0)
t.pendown()
# girandola rombo allungato
a=2
b=6
ip=(a**2+b**2)**1/2
t.color("purple")
t.begin_fill()
t.right(45/2)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(2*ip)
t.right(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.right(45)
t.forward(ip)
t.left(90)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.end_fill()
#girandola aperta
t.penup()
t.goto(200,0)
t.pendown()
angle4=t.heading()
print("angle4=",angle4)
t.left(67.5)
angle5=t.heading()
print("angle5=",angle5)
t.right(90)
a=12
b=30
y=(a**2+b**2)**(1/2)
t.left(45)
for i in range(0,1):
     t.begin_fill()
     t.color("pink")
     t.forward(y)
     t.right(90)
     t.forward(y)
     t.right(135)
     t.forward(2 * b)
     t.right(45)
     t.end_fill()
for i in range(1,2):
         t.begin_fill()
         t.color("light green")
         t.forward(y)
         t.right(90)
         t.forward(y)
         t.right(135)
         t.forward(2 * b)
         t.right(45)
         t.end_fill()
for i in range(2,3):
             t.begin_fill()
             t.color("grey")
             t.forward(y)
             t.right(90)
             t.forward(y)
             t.right(135)
             t.forward(2 * b)
             t.right(45)
             t.end_fill()
for i in range(4,5):
                 t.begin_fill()
                 t.color("brown")
                 t.forward(y)
                 t.right(90)
                 t.forward(y)
                 t.right(135)
                 t.forward(2 * b)
                 t.right(45)
                 t.end_fill()
#rombo
t.penup()
t.goto(0,200)
t.pendown()
angle6=t.heading()
print("angle6=",angle6)
t.right(45)
t.begin_fill()
t.color("red","red")
cateto1=20
cateto2=20
ip=(cateto1**2+cateto2**2)**(1/2)
for i in range(0,4):
    t.right(45)
    t.forward(ip)
    t.right(45)
t.end_fill()
xr1=t.xcor()
yr2=t.ycor()
print("xr1=",xr1,"yr2=",yr2)

t.color("yellow","yellow")
t.penup()
t.goto(20,180)
t.pendown()

#rombo 2 giallo
t.begin_fill()
for i in range(0,4):
    t.right(45)
    t.forward(ip)
    t.right(45)
t.end_fill()
t.penup()
t.goto(0,160)
t.pendown()

t.color("blue","blue")

t.begin_fill()
for i in range (0,4):
    t.right(45)
    t.forward(ip)
    t.right(45)
t.end_fill()
t.penup()
t.goto(-20,180)
t.pendown()
t.color("green","green")

t.begin_fill()
for i in range (0,4):
    t.right(45)
    t.forward(ip)
    t.right(45)
t.end_fill()
t.penup()
t.goto(0,120)
t.pendown()
#coda rombo
t.color("black")
t.circle(radius=-10,extent=180)
t.circle(radius=10,extent=180)
t.penup()
t.goto(100,250)
t.pendown()
angle7=t.heading()
print("angle7=",angle7)
t.right(45)
#girandola
b = 40
altezza = b / 2
k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
t.begin_fill()
t.color("red","red")
for i in range(0,2):
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
t.end_fill()
#girandola
t.penup()
t.goto(-100,250)
t.pendown()
t.left(45)
b = 40
altezza = b / 2
k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
t.begin_fill()
t.color("white","white")
for i in range(0,2):
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
t.end_fill()
#girandolaverdeitalia
t.penup()
t.goto(-200,150)
t.pendown()
t.left(45)
b = 40
altezza = b / 2
k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
t.begin_fill()
t.color("green","green")
for i in range(0,2):
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
t.end_fill()
t.penup()
t.goto(-400,150)
t.pendown()
t.right(45)
b = 12
altezza = b / 2
k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
t.begin_fill()
t.color("pink")
for i in range(0,2):
    t.left(45)
    t.forward(k)
    t.right(90)
    t.forward(k)
    t.right(135)
    t.forward(b)
    t.right(90)
    t.left(45)
    t.forward(k)
    t.right(90)
    t.forward(k)
    t.right(135)
    t.forward(b)
    t.right(90)
t.end_fill()
t.penup()
t.goto(-400,80)
t.pendown()
t.color("pink")
t.forward(50)
t.right(90)
t.color("brown")
t.begin_fill()
t.forward(50)
t.right(90)
t.forward(50)
c=50
i=(c**2+c**2)**(1/2)
t.right(135)
t.forward(i)
t.end_fill()
t.backward(i)
t.color("pink")
t.begin_fill()
t.left(45)
t.forward(c)
t.right(90)
t.forward(c)
t.right(135)
t.forward(i)
t.end_fill()
t.color("black")
#t.left(5)
t.circle(radius=40,extent=60)
t.circle(radius=-40,extent=60)
t.penup()
t.goto(500,-80)
t.pendown()
angle=t.heading()
print("angle=",angle)
t.right(135)
anglee=t.heading()
print("anglee=",anglee)
t.right(90)
#mongolfiera
t.color("blue")
t.begin_fill()
t.circle(radius=100,extent=360)
t.end_fill()
t.color("red")
t.begin_fill()
t.left(40)
t.circle(radius=100,extent=100)
t.left(80)
t.circle(radius=100,extent=100)
t.end_fill()
t.color("black")
angle=t.heading()
print(angle)
t.left(40)
angle2=t.heading()
print(angle2)
t.right(90)
t.forward(150)
x=t.xcor()
y=t.ycor()
print("x0=",x,"y0=",y)
t.backward(150)
x=t.xcor()
y=t.ycor()
print("x=",x,"y=",y)

t.penup()
t.goto(530,-75)
t.pendown()
t.right(20)
t.forward(88)
t.penup()
t.goto(470,-75)
t.pendown()
t.left(40)
t.forward(84)
t.backward(84)
t.pendown()
t.penup()
t.goto(499.9999999999877 ,-230.00000000000017)
t.pendown()

angle3=t.heading()
print(angle3)
t.color("brown")
t.begin_fill()
t.left(70)
t.forward(80)
t.backward(80)
t.right(180)
t.forward(80)
t.left(90)
t.forward(100)
t.left(90)
t.forward(160)
t.left(90)
t.forward(100)
t.end_fill()
t.right(45)
ca=25
ip=(ca**2+ca**2)**(1/2)
t.begin_fill()
t.forward(ip)
t.right(135)
t.forward(100)
t.right(45)
t.forward(ip)
t.right(135)
t.forward(100)
t.end_fill()
t.color("brown")
t.begin_fill()
t.left(90)
t.forward(160)
t.right(135)
t.forward(ip)
t.right(45)
t.forward(160)
t.end_fill()
x1=t.xcor()
y1=t.ycor()
print("x1=",x1,"y1=",y1)
t.penup()
t.goto(-500,100)
t.pendown()
#girandola rombo
angleeee=t.heading()
print(angleeee)
a=2.5
b=5
ip=(a**2+b**2)**1/2

t.color("light green")
t.begin_fill()
t.right(45/2)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(2*ip)
t.right(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.right(45)
t.forward(ip)
t.left(90)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.end_fill()
t.penup()
t.goto(-600,0)
t.pendown()
t.color("red")
angle=t.heading()
print("angle=",angle)
t.right(337.5)
angle22=t.heading()
print("angle22=",angle22)
t.right(45)
#girandola
a=2.5
b=7
ip=(a**2+b**2)**1/2

t.color("orange")
t.begin_fill()
t.right(45/2)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(2*ip)
t.right(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.right(45)
t.forward(ip)
t.left(90)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.end_fill()
t.penup()
t.goto(-500,-150)
t.pendown()
t.right(337.5)
t.right(45)
#girandola rombo
a=2.5
b=8
ip=(a**2+b**2)**1/2

t.color("black")
t.begin_fill()
t.right(45/2)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(2*ip)
t.right(45)
t.forward(ip)
t.right(135)
t.forward(ip)
t.right(45)
t.forward(ip)
t.left(90)
t.forward(ip)
t.left(45)
t.forward(ip)
t.left(135)
t.forward(ip)
t.left(45)
t.forward(ip)
t.end_fill()
t.penup()
t.goto(-300,-100)
t.pendown()
t.right(337.5)
t.right(45)
#aquilone
t.color("orange")
t.forward(50)
t.right(90)
t.color("orange")
t.begin_fill()
t.forward(50)
t.right(90)
t.forward(50)
c=50
i=(c**2+c**2)**(1/2)
t.right(135)
t.forward(i)
t.end_fill()
t.backward(i)
t.color("yellow")
t.begin_fill()
t.left(45)
t.forward(c)
t.right(90)
t.forward(c)
t.right(135)
t.forward(i)
t.end_fill()
t.color("black")
#t.left(5)
t.circle(radius=40,extent=60)
t.circle(radius=-40,extent=60)
t.penup()
t.goto(-50,-180)
t.pendown()
angle=t.heading()
print("angle=",angle)
t.right(135)
angle33=t.heading()
print("angle33=",angle33)
t.right(90)
#aquilone rombo
t.color("red")
t.begin_fill()
t.left(45)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.backward(ip)
t.left(135)
t.end_fill()
t.forward(20)
t.color("green")
t.begin_fill()
t.left(45)
t.forward(ip)
t.right(90)
t.forward(ip)
xcor=t.xcor()
ycor=t.ycor()
print("xcor=",xcor,"ycor=",ycor)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.left(45)
t.end_fill()
t.forward(10)
t.color("yellow")
t.begin_fill()
t.right(90)
t.forward(10)
t.left(45)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.left(45)
t.end_fill()
t.forward(10)

t.color("blue")
t.begin_fill()
t.forward(10)
t.left(45)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.right(90)
t.forward(ip)
t.end_fill()
t.penup()
t.goto(-25.16287431083036,-274.5113770675345)
t.pendown()
#coda aquilone
t.color("black")
t.right(140)
t.circle(radius=20,extent=150)
t.circle(radius=-20,extent=100)
t.penup()
t.goto(150,-150)
t.pendown()
angle44=t.heading()
print("angle44=",angle44)
t.right(135)
t.right(90)
#girandola
t.left(45)
b = 40
altezza = b / 2
k = (altezza ** 2 + altezza ** 2) ** (1 / 2)
t.begin_fill()
t.color("pink","pink")
for i in range(0,2):
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
        t.left(45)
        t.forward(k)
        t.right(90)
        t.forward(k)
        t.right(135)
        t.forward(b)
        t.right(90)
t.end_fill()



s.mainloop()