from turtle import *
d = Turtle()
m=Screen()
for _ in range(4):
    d.width(2)
    d.color("blue")
    d.forward(200)
    d.right(90)
    d.width(2)
    d.color("red")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("yellow")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("green")
    d.forward(150)
d.begin_fill()
for _ in range(0,1):
    d.width(2)
    d.color("blue","blue")
    d.forward(200)
    d.right(90)
    d.width(2)
    d.color("red","blue")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("yellow","blue")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("green","blue")
    d.forward(150)
    d.end_fill()
d.begin_fill()
for _ in range(1,2):
    d.width(2)
    d.color("blue","red")
    d.forward(200)
    d.right(90)
    d.width(2)
    d.color("red", "red")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("yellow", "red")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("green", "red")
    d.forward(150)
    d.end_fill()
d.begin_fill()
for _ in range(2,3):
    d.width(2)
    d.color("blue", "green")
    d.forward(200)
    d.right(90)
    d.width(2)
    d.color("red", "green")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("yellow", "green")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("green", "green")
    d.forward(150)
    d.end_fill()
d.begin_fill()
for _ in range(3,4):
    d.width(2)
    d.color("blue", "yellow")
    d.forward(200)
    d.right(90)
    d.width(2)
    d.color("red", "yellow")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("yellow", "yellow")
    d.forward(150)
    d.right(90)
    d.width(2)
    d.color("green", "yellow")
    d.forward(150)
    d.end_fill()
    d.penup()


m.mainloop()
