from turtle import Turtle,Screen
t=Turtle()
s=Screen()
a=int()
#t.width(10)
t.color("red")
t.speed("fastest")
for a in range(0,251):
    #t.begin_fill()
    t.left(45)
    t.forward(a)
    t.right(45)
    t.forward(a)
    t.right(45)
    t.forward(a)
    t.fillcolor("yellow")
    #t.end_fill()
    print("a=",a)
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)

s.mainloop()