from turtle import *
t=Turtle()
s=Screen()
a=int()
#t.width(10)
t.color("blue")
t.speed("fastest")
for a in range(0,491):
    t.begin_fill()
    t.right(135)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(2*a)
    t.fillcolor("light blue")
    t.end_fill()
s.mainloop()