from turtle import *
t=Turtle()
s=Screen()
b=20
a=(b**2+b**2)**(1/2)
for i in range(0,20):
    t.left(45)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(135)
    t.forward(3*b)
    t.right(180)
t.left(90)
for i in range(0,10):
    t.left(45)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(135)
    t.forward(3*b)
    t.right(180)
t.left(90)
for i in range(0,20):
    t.left(45)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(135)
    t.forward(3*b)
    t.right(180)
t.left(90)
for i in range(0,10):
    t.left(45)
    t.forward(a)
    t.right(90)
    t.forward(a)
    t.right(135)
    t.forward(3*b)
    t.right(180)
s.mainloop()