from turtle import *
t=Turtle()
s=Screen()
t.speed("fastest")
t.penup()
#s.bgcolor("black")
t.goto(-600,250)
t.pendown()
t.color("light blue")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()
t.penup()
t.goto(-600,150)
t.pendown()
t.color("pink")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    #t.fillcolor("light blue")
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()
t.penup()
t.goto(-600,50)
t.pendown()
t.color("yellow")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    #t.fillcolor("light blue")
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()

t.penup()
t.goto(-600,-50)
t.pendown()
t.color("purple")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    #t.fillcolor("light blue")
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()
t.penup()
t.goto(-600,-150)
t.pendown()
t.color("orange")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    #t.fillcolor("light blue")
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()

t.penup()
t.goto(-600,-250)
t.pendown()
t.color("brown")
for _ in range(0,13):
    t.begin_fill()
    t.circle(radius=40,extent=220)
    t.circle(radius=40,extent=140)
    #t.fillcolor("light blue")
    t.end_fill()
    x=t.xcor()
    y=t.ycor()
    print("x=",x,"y=",y)
    print("i=",_)
    t.penup()
    t.goto(x+100,y)
    t.pendown()
s.mainloop()